#!/usr/bin/env node
/**
 * @license
 * Copyright 2017 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Node.js server that provides Google auth services to Code City.
 * @author fraser@google.com (Neil Fraser)
 */

'use strict';

const crypto = require('crypto');
const forwardedParse = require('forwarded-parse');
const fs = require('fs').promises;
const {google} = require('googleapis');
const http = require('http');
const {URL, format: urlFormat} = require('url');

const oauth2Api = google.oauth2('v2');

// Configuration constants.
const configFileName = 'loginServer.cfg';

// Global variables
let CFG = null;
const /** !Object<string, !google.auth.OAuth2> */ clients = {};

const DEFAULT_CFG = {
  // Internal port for this HTTP server.  Nginx hides this from users.
  httpPort: 7781,
  // URL of connect page (absolute or relative).
  connectUrl: 'https://connect.example.codecity.world/',
  // URL of static folder (absolute or relative).
  staticUrl: 'https://static.example.codecity.world/',
  // Google's API client ID.
  clientId: '00000000000-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' +
      '.apps.googleusercontent.com',
  // Google's API client secret.
  clientSecret: 'yyyyyyyyyyyyyyyyyyyyyyyy',
  // Root domain.
  cookieDomain: 'example.codecity.world',
  // Random salt for login IDs.
  salt: 'zzzzzzzzzzzzzzzz',
  // Regexp on email addresses that must pass to allow access.
  emailRegexp: '.*'
};


/**
 * Serve an error to the given ServerResult.  Also log information
 * about the failed IncomingMessage to the console.
 * @param {!http.IncomingMessage} request The request which triggered the error.
 * @param {!http.ServerResponse} response The ServerResult to send error to.
 * @param {number} statusCode the HTTP response code to be served.
 * @param {string} message An additional message to include in the result.
 * @return {void}
 */
function sendError(request, response, statusCode, message) {
  console.log('%s %s (Host: %s): %d %s', request.method,
              request.url.replace(/=[^&]*(?=&|$)/g, '=...'),
              request.headers.host, statusCode, message);
  response.writeHead(statusCode).end(message);
}

/**
 * Load a file from disk, add substitutions, and serve to the web.
 * @param {!IncomingMessage} request The request being answered.
 * @param {!http.ServerResponse} response The ServerResult to send the file to.
 * @param {string} filename Name of template file on disk.
 * @param {!Object} subs Object-map of replacement strings.
 */
async function serveFile(request, response, filename, subs) {
  let /** string */ data;
  try {
    data = String(await fs.readFile(filename, 'utf8'));
  } catch (err) {
    sendError(request, response,
              500, `Unable to load file ${filename}: ${err}`);
    return;
  }
  // Inject substitutions.
  for (const name in subs) {
    data = data.replace(new RegExp(name, 'g'), subs[name]);
  }
  // Serve page to user.
  response.statusCode = 200;
  response.setHeader('Content-Type', 'text/html');
  response.end(data);
}

/**
 * Handles HTTP requests from web server.
 * @param {!Object} request HTTP server request object
 * @param {!Object} response HTTP server response object.
 */
async function handleRequest(request, response) {
  if (request.connection.remoteAddress !== '127.0.0.1') {
    sendError(request, response, 403,
              `Connection from ${request.connection.remoteAddress} denied.`);
    return;
  }

  // Determine what URL the client contacted us on.
  let proto = 'http';  // What proto we are actually listening to.
  let host = request.headers.host;  // Host header we actually received.
  // See if the first reverse proxy knows better.
  const forwarded = request.headers.forwarded;
  if (forwarded) {
    try {
      const forwards = forwardedParse(forwarded);
      if (forwards[0]) {
        if (forwards[0].proto) proto = forwards[0].proto;
        if (forwards[0].host) host = forwards[0].host;
      }
    } catch (e) {
      sendError(request, response, 400,
                `Forwarded header: ${e.name}: ${e.message} of "${forwarded}"`);
      return;
    }
  }
  const url = new URL(request.url, `${proto}://${host}`);
  const loginUrl = urlFormat(url, {fragment: false, search: false});

  // Get an authentication client for our interactions with Google.
  if (!clients[loginUrl]) {
    // Create client for login URL not seen before.
    clients[loginUrl] = new google.auth.OAuth2(
        CFG.clientId, CFG.clientSecret, loginUrl);
  }
  const oauth2Client = clients[loginUrl];

  // No auth code?  Serve login.html.
  const code = url.searchParams.get('code');
  if (!code) {
    // Compute Google's login URL, including deciding where to
    // redirect to afterwards.
    const options = {scope: 'email'};
    if (url.searchParams.has('after')) {
      options.state = url.searchParams.get('after');
    } else if (url.searchParams.has('loginThenClose')) {
      options.state = CFG.staticUrl + 'login-close.html';
    } else {
      options.state = CFG.connectUrl;
    }
    const subs = {
      '<<<OAUTH_URL>>>': oauth2Client.generateAuthUrl(options),
      '<<<STATIC_URL>>>': CFG.staticUrl
    };
    serveFile(request, response, 'login.html', subs);
    return;
  }

  // Handle the result of a login.
  let tokens;
  try {
    ({tokens} = await oauth2Client.getToken(code));
  } catch (err) {
    sendError(request, response, 500, `Google OAuth2 fail: ${err}`);
    return;
  }
  // Now tokens contains an access_token and an optional
  // refresh_token. Save them.
  oauth2Client.setCredentials(tokens);
  let data;
  try {
    ({data} = await oauth2Api.userinfo.v2.me.get({auth: oauth2Client}));
  } catch (err) {
    sendError(request, response, 500, `Google Userinfo fail: ${err}`);
    return;
  }
  // Convert the Google ID into one unique for Code City.
  const id = crypto.createHash('sha512')
      .update(CFG.salt + data.id).digest('hex');
  const emailRegexp = new RegExp(CFG.emailRegexp || '.*');
  // FYI: If present, data.hd contains the GSfE domain.
  // E.g. 'students.gissv.org', or 'sjsu.edu'.
  // We aren't using it now, but this might be used to filter users.

  // Check email address is allowed.
  if (!emailRegexp.test(data.email)) {
    sendError(request, response, 403, `Login denied for ${data.email}`);
    return;
  }

  // Login successful.  Issue ID cookie.
  if (!url.searchParams.has('state')) {
    sendError(request, response, 500,
              'Login successful but loginServer forgot where to redirect to.');
    return;
  }
  const domain = CFG.cookieDomain ? `Domain=${CFG.cookieDomain}; ` : '';
  const redirectUrl = url.searchParams.get('state');

  response.writeHead(302, {  // Temporary redirect.
    'Set-Cookie': `ID=${id}; HttpOnly; ${domain}Path=/`,
    'Location': redirectUrl,
  });
  response.end('Login OK.  Redirecting.');
  console.log('Accepted xxxx' + id.substring(id.length - 4));
}

/**
 * Read the JSON configuration file and return it.  If none is
 * present, write a stub and throw an error.
 */
async function readConfigFile(filename) {
  let data;
  try {
    data = await fs.readFile(filename, 'utf8');
  } catch (err) {
    console.log(`Configuration file ${filename} not found.  ` +
        'Creating new file.');
    data = JSON.stringify(DEFAULT_CFG, null, 2) + '\n';
    await fs.writeFile(filename, data, 'utf8');
  }
  CFG = JSON.parse(data);
  if (!CFG.salt || CFG.salt === DEFAULT_CFG.salt) {
    throw Error(
        `Configuration file ${filename} not configured.  ` +
        'Please edit this file.');
  }
  if (!CFG.connectUrl.endsWith('/')) CFG.connectUrl += '/';
  if (!CFG.staticUrl.endsWith('/')) CFG.staticUrl += '/';
}

/**
 * Read configuration and start up the HTTP server.
 */
async function startup() {
  await readConfigFile(configFileName);

  // Start an HTTP server.
  const server = http.createServer(handleRequest);
  server.listen(CFG.httpPort, 'localhost', () => {
    console.log(`Login server listening on port ${CFG.httpPort}`);
  });
}

startup();
