/**
 * @license
 * Copyright 2017 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Host objects for Code City.
 */

//////////////////////////////////////////////////////////////////////
// AUTO-GENERATED CODE FROM DUMP.  EDIT WITH CAUTION!
//////////////////////////////////////////////////////////////////////

$.hosts = {};

$.hosts.root = (new 'Object.create')($.servers.http.Host.prototype);

$.hosts.root.subdomains = (new 'Object.create')(null);

$.hosts.root.hostname = 'google.codecity.world';

$.hosts.root['/'] = {};
$.hosts.root['/'].www = function jssp(request, response) {
  // DO NOT EDIT THIS CODE.  AUTOMATICALLY GENERATED BY JSSP.
  // To edit contents of generated page, edit this.source.
  return jssp.render(this, request, response);  // See $.Jssp for explanation.
};
Object.setPrototypeOf($.hosts.root['/'].www, $.Jssp.prototype);
Object.setOwnerOf($.hosts.root['/'].www, $.physicals.Maximilian);
Object.setOwnerOf($.hosts.root['/'].www.prototype, $.physicals.Maximilian);
$.hosts.root['/'].www.source = '<!doctype html>\n<% var staticUrl = request.hostUrl(\'static\'); %>\n<html lang="en">\n<head>\n  <title>Code City</title>\n  <style>\n    body {\n      font-family: "Roboto Mono", monospace;\n      text-align: center;\n    }\n    h1 {\n      font-size: 40pt;\n      font-weight: 100;\n    }\n    h1>img {\n      vertical-align: text-bottom;\n    }\n    #tagline {\n      font-style: italic;\n      margin: 2em;\n    }\n    iframe {\n      height: 50px;\n      width: 100px;\n      border: none;\n      display: block;\n      margin: 0 auto;\n    }\n  </style>\n  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">\n  <link href="<%=staticUrl%>favicon.ico" rel="shortcut icon">\n</head>\n<body>\n  <h1>\n    <img src="<%=staticUrl%>logo.svg" alt="" width="95" height="100">\n    Code City\n  </h1>\n  <p id="tagline">A community of inquisitive programmers.</p>\n  <iframe src="<%=request.hostUrl(\'login\')%>?after=<%=request.hostUrl(\'connect\')%>"></iframe>\n</body>\n</html>';
$.hosts.root['/'].www.hash_ = '5a3670775f8907f45bb4ac2ea9c2b68bv1.0.0';
$.hosts.root['/'].www.compiled_ = function(request, response) {
// DO NOT EDIT THIS CODE: AUTOMATICALLY GENERATED BY JSSP.
response.write("<!doctype html>\n");
 var staticUrl = request.hostUrl('static'); 
response.write("\n<html lang=\"en\">\n<head>\n  <title>Code City</title>\n  <style>\n    body {\n      font-family: \"Roboto Mono\", monospace;\n      text-align: center;\n    }\n    h1 {\n      font-size: 40pt;\n      font-weight: 100;\n    }\n    h1>img {\n      vertical-align: text-bottom;\n    }\n    #tagline {\n      font-style: italic;\n      margin: 2em;\n    }\n    iframe {\n      height: 50px;\n      width: 100px;\n      border: none;\n      display: block;\n      margin: 0 auto;\n    }\n  </style>\n  <link href=\"https://fonts.googleapis.com/css?family=Roboto+Mono\" rel=\"stylesheet\">\n  <link href=\"");
response.write(staticUrl);
response.write("favicon.ico\" rel=\"shortcut icon\">\n</head>\n<body>\n  <h1>\n    <img src=\"");
response.write(staticUrl);
response.write("logo.svg\" alt=\"\" width=\"95\" height=\"100\">\n    Code City\n  </h1>\n  <p id=\"tagline\">A community of inquisitive programmers.</p>\n  <iframe src=\"");
response.write(request.hostUrl('login'));
response.write("?after=");
response.write(request.hostUrl('connect'));
response.write("\"></iframe>\n</body>\n</html>");
};
Object.setOwnerOf($.hosts.root['/'].www.compiled_, $.physicals.Neil);
Object.setOwnerOf($.hosts.root['/'].www.compiled_.prototype, $.physicals.Neil);
Object.defineProperty($.hosts.root['/'].www.compiled_, 'name', {value: "$.www['/'].www.compiled_"});

$.hosts.root['/mirror'] = {};
Object.setOwnerOf($.hosts.root['/mirror'], $.physicals.Maximilian);
// CLOSURE: type: function, vars: source, jssp
// CLOSURE: type: funexp, vars: Jssp
$.hosts.root['/mirror'].www = function jssp(request, response) {
  // DO NOT EDIT THIS CODE.  AUTOMATICALLY GENERATED BY JSSP.
  // To edit contents of generated page, edit this.source.
  return jssp.render(this, request, response);  // See $.Jssp for explanation.
};
Object.setPrototypeOf($.hosts.root['/mirror'].www, $.Jssp.prototype);
Object.setOwnerOf($.hosts.root['/mirror'].www, $.physicals.Maximilian);
Object.setOwnerOf($.hosts.root['/mirror'].www.prototype, $.physicals.Neil);
$.hosts.root['/mirror'].www.source = "<!doctype html>\n<% var staticUrl = request.hostUrl('static'); %>\n<html>\n  <head>\n    <title>Code City Browser Mirror</title>\n    <style>\n      body {\n        font-family: \"Roboto Mono\", monospace;\n      }\n      h1 {\n        text-align: center;\n      }\n      h1>img {\n        vertical-align: text-bottom;\n      }\n    </style>\n    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Mono\" rel=\"stylesheet\">\n    <link href=\"<%=staticUrl%>favicon.ico\" rel=\"shortcut icon\">\n  </head>\n  <body>\n    <h1>\n      <img src=\"<%=staticUrl%>logo.svg\" alt=\"\" width=\"47.5\" height=\"50\">\n      Code City Browser Mirror\n    </h1>\n<%\nfor (var key in request) {\n  if (!request.hasOwnProperty(key)) continue;\n  var value = request[key];\n  \n  response.write('<h2>request.' + $.utils.html.escape(key) + ':</h2>\\n');\n  response.write('<pre>');\n  if (key === 'user') {\n    response.write(value ? $.utils.html.escape(value.name) : value + '\\n');\n  } else if ($.utils.isObject(value) ) {\n    for (var subkey in value) {\n      var valueString;\n      try {\n        valueString = JSON.stringify(value[subkey], undefined, 2);\n      } catch (e) {\n        valueString = String(e);\n      }\n      response.write($.utils.html.escape(subkey + ': ' + valueString) + '\\n');\n    }\n  } else {\n      response.write($.utils.html.escape($.utils.code.toSource(value)) + '\\n');\n  }\n  response.write('</pre>');\n}\n%>\n    <h2>request.fromSameOrigin():</h2>\n    <pre><%= request.fromSameOrigin() %></pre>\n    <p>Done</p>\n  </body>\n</html>";
$.hosts.root['/mirror'].www.hash_ = '54daf9461fdae69d15210d37523a1ae5v1.0.0';
$.hosts.root['/mirror'].www.compiled_ = function(request, response) {
// DO NOT EDIT THIS CODE: AUTOMATICALLY GENERATED BY JSSP.
response.write("<!doctype html>\n");
 var staticUrl = request.hostUrl('static'); 
response.write("\n<html>\n  <head>\n    <title>Code City Browser Mirror</title>\n    <style>\n      body {\n        font-family: \"Roboto Mono\", monospace;\n      }\n      h1 {\n        text-align: center;\n      }\n      h1>img {\n        vertical-align: text-bottom;\n      }\n    </style>\n    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Mono\" rel=\"stylesheet\">\n    <link href=\"");
response.write(staticUrl);
response.write("favicon.ico\" rel=\"shortcut icon\">\n  </head>\n  <body>\n    <h1>\n      <img src=\"");
response.write(staticUrl);
response.write("logo.svg\" alt=\"\" width=\"47.5\" height=\"50\">\n      Code City Browser Mirror\n    </h1>\n");

for (var key in request) {
  if (!request.hasOwnProperty(key)) continue;
  var value = request[key];
  
  response.write('<h2>request.' + $.utils.html.escape(key) + ':</h2>\n');
  response.write('<pre>');
  if (key === 'user') {
    response.write(value ? $.utils.html.escape(value.name) : value + '\n');
  } else if ($.utils.isObject(value) ) {
    for (var subkey in value) {
      var valueString;
      try {
        valueString = JSON.stringify(value[subkey], undefined, 2);
      } catch (e) {
        valueString = String(e);
      }
      response.write($.utils.html.escape(subkey + ': ' + valueString) + '\n');
    }
  } else {
      response.write($.utils.html.escape($.utils.code.toSource(value)) + '\n');
  }
  response.write('</pre>');
}

response.write("\n    <h2>request.fromSameOrigin():</h2>\n    <pre>");
response.write(request.fromSameOrigin());
response.write("</pre>\n    <p>Done</p>\n  </body>\n</html>");
};
Object.setOwnerOf($.hosts.root['/mirror'].www.compiled_, $.physicals.Neil);
Object.setOwnerOf($.hosts.root['/mirror'].www.compiled_.prototype, $.physicals.Neil);
Object.defineProperty($.hosts.root['/mirror'].www.compiled_, 'name', {value: "$.hosts.root['/mirror'].www.compiled_"});

$.hosts.root['/robots.txt'] = {};
$.hosts.root['/robots.txt'].www = function jssp(request, response) {
  // DO NOT EDIT THIS CODE.  AUTOMATICALLY GENERATED BY JSSP.
  // To edit contents of generated page, edit this.source.
  return jssp.render(this, request, response);  // See $.Jssp for explanation.
};
Object.setPrototypeOf($.hosts.root['/robots.txt'].www, $.Jssp.prototype);
Object.setOwnerOf($.hosts.root['/robots.txt'].www, $.physicals.Maximilian);
Object.setOwnerOf($.hosts.root['/robots.txt'].www.prototype, $.physicals.Maximilian);
$.hosts.root['/robots.txt'].www.source = "<% response.setHeader('Content-Type', 'text/plain; charset=utf-8') %>\n# Don't index this Code City instance at this time.\nUser-agent: *\nDisallow: /";
$.hosts.root['/robots.txt'].www.hash_ = '93d21ff90a36d1fb6bcf5d7cb4f5add3v1.0.0';
$.hosts.root['/robots.txt'].www.compiled_ = function(request, response) {
// DO NOT EDIT THIS CODE: AUTOMATICALLY GENERATED BY JSSP.
 response.setHeader('Content-Type', 'text/plain; charset=utf-8') 
response.write("\n# Don't index this Code City instance at this time.\nUser-agent: *\nDisallow: /");
};
delete $.hosts.root['/robots.txt'].www.compiled_.name;
Object.setOwnerOf($.hosts.root['/robots.txt'].www.compiled_, $.physicals.Maximilian);
Object.setOwnerOf($.hosts.root['/robots.txt'].www.compiled_.prototype, $.physicals.Maximilian);

$.hosts.dummy = (new 'Object.create')($.servers.http.Host.prototype);
Object.setOwnerOf($.hosts.dummy, $.physicals.Maximilian);
$.hosts.dummy.hostname = undefined;
$.hosts.dummy.handle = function handle(request, response, info) {
  /* Report the mishandling of an http(s) request which should have
   * been intercepted by the nginx front-end and proxied to one
   * of the other servers.
   *
   * This Host object is a singleton placeholer to mark (in
   * $.hosts.root.subdomains) the subdomains that should be directed
   * to loginServer, connectServer, etc., or served from the /static/
   * directory.  As such, no requests should ever be able to reach
   * this Host object except due to a misconfiguration of nginx.
   *
   * Arguments:
   * - request: $.servers.http.Request - the incoming request to handle.
   * - response: $.servers.http.Response - the response to write to.
   * - info: Object - some information used by recursive calls to this function.
   * Returns: boolean - always true as all requests successfully generate
   *     an error message.
   */
  response.sendError(500, 'This request should have been intercepted by ' +
                     'the reverse proxy.  Check nginx configuration!');
  return true;
};
Object.setOwnerOf($.hosts.dummy.handle, $.physicals.Maximilian);
Object.setOwnerOf($.hosts.dummy.handle.prototype, $.physicals.Maximilian);

$.hosts.root.subdomains.connect = $.hosts.dummy;

$.hosts.root.subdomains.login = $.hosts.dummy;

$.hosts.root.subdomains.mobwrite = $.hosts.dummy;

$.hosts.root.subdomains.static = $.hosts.dummy;

$.hosts.root.subdomains.system = (new 'Object.create')($.servers.http.Host.prototype);
$.hosts.root.subdomains.system['/logout'] = {};
Object.setOwnerOf($.hosts.root.subdomains.system['/logout'], $.physicals.Neil);
// CLOSURE: type: function, vars: source, jssp
// CLOSURE: type: funexp, vars: Jssp
$.hosts.root.subdomains.system['/logout'].www = function jssp(request, response) {
  // DO NOT EDIT THIS CODE.  AUTOMATICALLY GENERATED BY JSSP.
  // To edit contents of generated page, edit this.source.
  return jssp.render(this, request, response);  // See $.Jssp for explanation.
};
Object.setPrototypeOf($.hosts.root.subdomains.system['/logout'].www, $.Jssp.prototype);
Object.setOwnerOf($.hosts.root.subdomains.system['/logout'].www, $.physicals.Neil);
Object.setOwnerOf($.hosts.root.subdomains.system['/logout'].www.prototype, $.physicals.Neil);
$.hosts.root.subdomains.system['/logout'].www.source = '<%\nvar staticUrl = request.hostUrl(\'static\');\nvar doLogout = !request.user ||\n    (request.query === \'execute\' && request.fromSameOrigin());\nif (doLogout) {\n  response.clearIdCookie()\n}\n%>\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Code City Logout</title>\n  <style>\n    body {\n      font-family: "Roboto Mono", monospace;\n      text-align: center;\n    }\n    h1 {\n      font-size: 40pt;\n      font-weight: 100;\n    }\n    h1>img {\n      vertical-align: text-bottom;\n    }\n    #tagline {\n      font-style: italic;\n      margin: 2em;\n    }\n    iframe {\n      height: 50px;\n      width: 100px;\n      border: none;\n      display: block;\n      margin: 0 auto;\n    }\n  </style>\n  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">\n  <link href="<%=staticUrl%>favicon.ico" rel="shortcut icon">\n  <link href="<%=staticUrl%>style/jfk.css" rel="stylesheet">\n\n  </head>\n<body>\n  <h1>\n    <img src="<%=staticUrl%>logo.svg" alt="" width="95" height="100">\n    Code City\n  </h1>\n  <p id="tagline"><%= $.servers.http.host %></p>\n<% if (doLogout) { %>\n  <p>You have been signed out.</p>\n  <iframe src="<%=request.hostUrl(\'login\')%>"></iframe>\n<% } else { %>\n  <div class="jfk-button jfk-button-action" role="button" id="signout">\n    Sign out\n  </div>\n  <script>\n    var button =  document.getElementById(\'signout\');\n    button.addEventListener(\'click\', function() {\n      parent.location = "?execute";\n    });\n  </script>\n<% } %>\n</body>\n</html>';
$.hosts.root.subdomains.system['/logout'].www.hash_ = 'a14e8b71680854ad46e94a3bf2676e2fv1.0.0';
$.hosts.root.subdomains.system['/logout'].www.compiled_ = function(request, response) {
// DO NOT EDIT THIS CODE: AUTOMATICALLY GENERATED BY JSSP.

var staticUrl = request.hostUrl('static');
var doLogout = !request.user ||
    (request.query === 'execute' && request.fromSameOrigin());
if (doLogout) {
  response.clearIdCookie()
}

response.write("\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Code City Logout</title>\n  <style>\n    body {\n      font-family: \"Roboto Mono\", monospace;\n      text-align: center;\n    }\n    h1 {\n      font-size: 40pt;\n      font-weight: 100;\n    }\n    h1>img {\n      vertical-align: text-bottom;\n    }\n    #tagline {\n      font-style: italic;\n      margin: 2em;\n    }\n    iframe {\n      height: 50px;\n      width: 100px;\n      border: none;\n      display: block;\n      margin: 0 auto;\n    }\n  </style>\n  <link href=\"https://fonts.googleapis.com/css?family=Roboto+Mono\" rel=\"stylesheet\">\n  <link href=\"");
response.write(staticUrl);
response.write("favicon.ico\" rel=\"shortcut icon\">\n  <link href=\"");
response.write(staticUrl);
response.write("style/jfk.css\" rel=\"stylesheet\">\n\n  </head>\n<body>\n  <h1>\n    <img src=\"");
response.write(staticUrl);
response.write("logo.svg\" alt=\"\" width=\"95\" height=\"100\">\n    Code City\n  </h1>\n  <p id=\"tagline\">");
response.write($.servers.http.host);
response.write("</p>\n");
 if (doLogout) { 
response.write("\n  <p>You have been signed out.</p>\n  <iframe src=\"");
response.write(request.hostUrl('login'));
response.write("\"></iframe>\n");
 } else { 
response.write("\n  <div class=\"jfk-button jfk-button-action\" role=\"button\" id=\"signout\">\n    Sign out\n  </div>\n  <script>\n    var button =  document.getElementById('signout');\n    button.addEventListener('click', function() {\n      parent.location = \"?execute\";\n    });\n  </script>\n");
 } 
response.write("\n</body>\n</html>");
};
Object.setOwnerOf($.hosts.root.subdomains.system['/logout'].www.compiled_, $.physicals.Neil);
Object.setOwnerOf($.hosts.root.subdomains.system['/logout'].www.compiled_.prototype, $.physicals.Neil);
Object.defineProperty($.hosts.root.subdomains.system['/logout'].www.compiled_, 'name', {value: "$.hosts.system['/logout'].www.compiled_"});

$.hosts.test = (new 'Object.create')($.servers.http.Host.prototype);

$.hosts.test.subdomains = (new 'Object.create')(null);

$.hosts.test.hostname = 'test.google.codecity.world';

$.hosts.test.pathToSubdomain = true;

$.hosts.test['/'] = $.hosts.root['/'];

$.hosts.test['/error'] = {};
Object.setOwnerOf($.hosts.test['/error'], $.physicals.Maximilian);
$.hosts.test['/error'].www = function www_error_www(request, response) {
  throw new Error('this is a test Error');
};
Object.setOwnerOf($.hosts.test['/error'].www, $.physicals.Maximilian);
Object.setOwnerOf($.hosts.test['/error'].www.prototype, $.physicals.Maximilian);

$.hosts.test['/mirror'] = $.hosts.root['/mirror'];

$.hosts.test.subdomains.connect = $.hosts.dummy;

$.hosts.test.subdomains.login = $.hosts.dummy;

$.hosts.test.subdomains.mobwrite = $.hosts.dummy;

$.hosts.test.subdomains.static = $.hosts.dummy;

$.hosts.test.subdomains.system = $.hosts.root.subdomains.system;

