/**
 * @license
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Start core database.  Note that, unlike most of the
 * rest of the files in the core/ directory, this is hand-written.
 *
 * It assumed this file will be used when starting a full database
 * dump; for that, a file in database/, generated by dump, will
 * restart listeners intead.
 */

/* Optional (but recommended) configuration.  The web server is
 * capable of guessing its own hostname, but will be more efficient
 * and secure if its configuration is specified explicitly.
 */

/* Set .hostname to the canonical hostname (including the port number,
 * if non-default).
 */
// $.hosts.root.hostname = 'example.codecity.world';
// $.hosts.root.hostname = 'localhost:8080';

/* If your host has more than one name, set .hostRegExp to a regular
 * expression that matches all valid name+port combinations for this
 * host.  It is recommended that it end with /$/, but do NOT start it
 * with /^/ unless you want to break wildcard subdomains.  Make sure
 * it matches .hostname!
 */
// Accept either of two different hostnames.
// $.hosts.root.hostRegExp = /example.codecity.world$|codecity.example.com$/;
// Match any TLD and optional port.
// $.hosts.root.hostRegExp = /example.codecity.\w+(?::\d+)?$/;

/* Set .pathToSubdomain to true if you don't have a wildcard DNS entry
 * and wildcard TLS certificate for your hostname (false if you do);
 * this will enable accessing pages usually served on subdomains (such
 * as the code editor) via the root hostname instead.
 *
 * Normally the nginx reverse proxy sends a CodeCity-pathToSubdomain
 * header which will automatically enable or disable this feature, but
 * you can override it here.
 */
// $.hosts.root.pathToSubdomain = false;

// Set up.
$.system.onStartup();

// Tidy up.
$.clock.movable = true;
$.clock.moveTo($.startRoom);
$.clock.movable = false;

$.tutorial.moveTo($.startRoom);
$.tutorial.reset();

$.pot.moveTo($.startRoom);
$.pot.stage = 0;
$.seed.moveTo($.startRoom);
$.thrower.moveTo($.startRoom);

$.cage.moveTo($.physicals['Genetics Lab']);

$.assistant.moveTo($.startRoom);


