#!/bin/bash

# Compile server
closure-compiler --flagfile compile.flag --entry_point=codecity.js codecity.js

# Compile tests
closure-compiler --flagfile compile.flag --entry_point=tests/run.js tests/**.js
