#!/usr/bin/env node --harmony-weak-refs
/**
 * @license
 * Copyright 2018 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @fileoverview Read Eval Print Loop (REPL) for JavaScript Interpreter.
 * @author cpcallen@google.com (Christopher Allen)
 */
'use strict';

const readline = require('readline');
const Interpreter = require('./interpreter');
const fs = require('fs');

const intrp = new Interpreter;
intrp.createThreadForSrc(fs.readFileSync('startup/es5.js', 'utf8'));
intrp.run();
intrp.createThreadForSrc(fs.readFileSync('startup/es6.js', 'utf8'));
intrp.run();
intrp.createThreadForSrc(fs.readFileSync('startup/es7.js', 'utf8'));
intrp.run();
intrp.createThreadForSrc(fs.readFileSync('startup/esx.js', 'utf8'));
intrp.run();
intrp.createThreadForSrc(fs.readFileSync('startup/cc.js', 'utf8'));
intrp.run();

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  removeHistoryDuplicates: true,
});

rl.prompt();
rl.on('line', function(line) {
  try {
    let thread;
    try {
      thread = intrp.createThreadForSrc(line).thread;
    } catch (e) {
      console.log('%s: %s', e.name, e.message);
      return;
    }
    intrp.run();
    console.log(intrp.pseudoToNative(thread.value));
  } finally {
    rl.prompt();
  }
}).on('close', function() {
  process.exit(0);
});
